"""Read-only mailbox provider contract."""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any

class MailboxProvider(ABC):
    def connect(self) -> None: ...
    @abstractmethod
    def verify_connection(self) -> dict[str, Any]: ...
    @abstractmethod
    def fetch_new_messages(self, cursor: str | None, *, batch_size: int) -> tuple[list[dict[str, Any]], str | None]: ...
    @abstractmethod
    def fetch_message(self, message_id: str) -> dict[str, Any]: ...
    @abstractmethod
    def fetch_thread(self, thread_id: str) -> list[dict[str, Any]]: ...
    @abstractmethod
    def fetch_attachments(self, message: dict[str, Any]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def refresh_connection(self) -> None: ...
    @abstractmethod
    def get_connection_status(self) -> str: ...
    def disconnect(self) -> None: ...
    def get_sync_cursor(self) -> str | None: ...
    def save_sync_cursor(self, cursor: str | None) -> None: ...
